version: '3.8'

services:
  cozysoccerchamp.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000
    container_name: cozysoccerchamp.api
    image: cozysoccerchamp.api
    build:
      context: ./src/Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
       - ./src/Backend/Server/CozySoccerChamp.Api/CozySoccerChamp.db:/app/CozySoccerChamp.db

  cozysoccerchamp.webclient:
    container_name: cozysoccerchamp.webclient
    image: cozysoccerchamp.webclient
    build:
      context: ./src/Client/react-web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - cozysoccerchamp.api