services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/ssl:/etc/ssl'
    depends_on:
      - "cozysoccerchamp.api"
      - "cozysoccerchamp.webclient"
    networks:
      - prod-network

  cozysoccerchamp.api:
    environment:
      - ASPNETCORE_HTTP_PORTS=8000
      - ConnectionStrings__CozySoccerChampPostgresSqlConnection=""
      - BotSettings__BotToken=""
      - BotSettings__HostAddress=""
      - BotSettings__SecretToken=""
      - BotSettings__ClientUrl=""
      - SoccerApiSettings__ApiToken=""
    container_name: cozysoccerchamp.api
    image: cozysoccerchamp.api
    build:
      context: ./src/Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - prod-network
    
  cozysoccerchamp.webclient:
    container_name: cozysoccerchamp.webclient
    image: cozysoccerchamp.webclient
    build:
      context: ./src/Client/react-web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge